可以认为NumPy就是Python中的Matlab，用于进行科学计算，其主要功能是更方便高效的处理多维度数组（向量，矩阵，张量）。
第一步就是要导入NumPy工具包

In [2]:
#encoding:utf-8
import numpy as np

### 数组Arrays

多维度表格，通过数值进行索引。

初始化数组：

In [3]:
a = np.array([1, 2, 3])  # 创建维度为1的数组
print type(a), a.shape, a[0], a[1], a[2]
a[0] = 5                 # 赋值
print a  

<type 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])   # 创建二维数组(rank为2)
print b

[[1 2 3]
 [4 5 6]]


In [5]:
print b.shape #查看形状                   
print b[0, 0], b[0, 1], b[1, 0]

(2, 3)
1 2 4


Numpy也提供了一些其他方式创建特殊数组：

In [6]:
a = np.zeros((2,2)) 
print a

[[ 0.  0.]
 [ 0.  0.]]


In [7]:
b = np.ones((1,2))
print b

[[ 1.  1.]]


In [8]:
c = np.full((2,2), 7) # 值全部为7的2*2数组
print c 

[[ 7.  7.]
 [ 7.  7.]]


/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [9]:
d = np.eye(2)
print d

[[ 1.  0.]
 [ 0.  1.]]


In [10]:
e = np.random.random((2,2)) # 值为随机（0-1）的矩阵
print e

[[ 0.69711138  0.46232798]
 [ 0.5407355   0.31567818]]


### 数组的索引

Numpy提供了多种方式对数组内容进行索引。

In [15]:
# 创建下面的rank为2形状为(3, 4)的数组
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [16]:
b = a[:2, 1:3]
print b

[[2 3]
 [6 7]]


In [17]:
print a[0, 1]  
b[0, 0] = 77    # b[0, 0]于a[0, 1]值相同，该操作也会修改a的值，b只是a的一个镜像（不是创建了一个新的数组）
print a[0, 1] 

2
77


In [18]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print a
row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r3 = a[[1], :]
print row_r1, row_r1.shape 
print row_r2, row_r2.shape
print row_r3, row_r3.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [19]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print col_r1, col_r1.shape
print
print col_r2, col_r2.shape

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [20]:
a = np.array([[1,2], [3, 4], [5, 6]])

print a[[0, 1, 2], [0, 1, 0]]
# 上式于下面的获得相同结果
print np.array([a[0, 0], a[1, 1], a[2, 0]])

[1 4 5]
[1 4 5]


In [21]:
print a[[0, 1, 2], [0, 1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

一些置换矩阵位置值的小技巧：

In [22]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print a

b = np.array([0, 2, 0, 1])
print a[np.arange(4), b]  # 结果为"[ 1  6  7 11]"

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]


In [23]:
a[np.arange(4), b] += 10 #每个元素都会加上10
print a 

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


条件选值

In [24]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)

print bool_idx

[[False False]
 [ True  True]
 [ True  True]]


In [25]:
print a[bool_idx]

print a[a > 2]

[3 4 5 6]
[3 4 5 6]


### 数据类型

In [27]:
x = np.array([1, 2])
y = np.array([1.0, 2.0])
z = np.array([1, 2], dtype=np.int64)  # 强制制定数据类型，推荐

print x.dtype, y.dtype, z.dtype

int64 float64 int64


### 数组中数学操作

In [28]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# 元素级别的操作
print x + y
print np.add(x, y)

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [29]:
print x - y
print np.subtract(x, y)

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [30]:
print x * y
print np.multiply(x, y)

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


In [31]:
print x / y
print np.divide(x, y)

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [32]:
print np.sqrt(x)

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [34]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [35]:
# 向量內积（点成）
print v.dot(w)
print np.dot(v, w)

219
219


In [36]:
# 矩阵向量相乘
print x.dot(v)
print np.dot(x, v)

[29 67]
[29 67]


In [37]:
# 矩阵矩阵相乘
print x.dot(y)
print np.dot(x, y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


一些其他有用的函数

In [38]:
x = np.array([[1,2],[3,4]])

print np.sum(x)
print np.sum(x, axis=0)
print np.sum(x, axis=1)  

10
[4 6]
[3 7]


In [39]:
print x
print x.T #矩阵转置

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [41]:
v = np.array([[1,2,3]])
print v 
print v.T

[[1 2 3]]
[[1]
 [2]
 [3]]


### Broadcasting，广播操作

In [42]:
# 比如，我们想为矩阵中的每行加上一个固定的向量

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

for i in range(4):
    y[i, :] = x[i, :] + v

print y

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [43]:
# 当数据很大的时候，循环效率比较低。
vv = np.tile(v, (4, 1))  # 获得4个v的copy
print vv

y = x + vv  # Add x and vv elementwise
print y

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [44]:
vv = np.tile(v, (4, 2))  # 获得4个v的copy，每行两个v
print vv

[[1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]]


In [45]:
# 更简便的方式

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
print y

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
