In [3]:
# encoding:utf-8
import numpy as np
import tensorflow as tf

### 卷积操作示意

In [6]:
# 输入数据（图像）
x_image = tf.placeholder(tf.float32, shape=[5,5])
x = tf.reshape(x_image, [1, 5, 5, 1])

In [7]:
# 滤波器
W_cpu = np.array([[1,1,1], [0,-1, 0], [0, -1, 1]], dtype=np.float32)
W = tf.Variable(W_cpu)
W = tf.reshape(W, [3, 3, 1, 1])

In [8]:
# 步长,卷积类型
strides = [1, 1, 1, 1]
padding = 'VALID'

# 卷积
y = tf.nn.conv2d(x, W, strides, padding)

In [9]:
x_data = np.array(
    [
        [1,0,0,0,0],
        [2,1,1,2,1],
        [1,1,2,2,0],
        [2,2,1,0,0],
        [2,1,2,1,1]        
    ]
)

In [10]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    x = sess.run(x, feed_dict={x_image:x_data})
    W = sess.run(W, feed_dict={x_image:x_data})
    y = sess.run(y, feed_dict={x_image:x_data})
    

In [13]:
print "The shape of X: ", x.shape
print x.reshape(5, 5)
print ""

print "The shape of W: ", W.shape
print W.reshape(3, 3)
print ""

print "The shape of y: ", y.shape
print y.reshape(3, 3)
print ""

The shape of X:  (1, 5, 5, 1)
[[ 1.  0.  0.  0.  0.]
 [ 2.  1.  1.  2.  1.]
 [ 1.  1.  2.  2.  0.]
 [ 2.  2.  1.  0.  0.]
 [ 2.  1.  2.  1.  1.]]

The shape of W:  (3, 3, 1, 1)
[[ 1.  1.  1.]
 [ 0. -1.  0.]
 [ 0. -1.  1.]]

The shape of y:  (1, 3, 3, 1)
[[ 1. -1. -4.]
 [ 2.  1.  2.]
 [ 3.  3.  4.]]



### 池化操作示意

In [14]:
# 输入X
x_image = tf.placeholder(tf.float32, shape=[4,4])
x = tf.reshape(x_image, [1, 4, 4, 1])

# ksize & Stride & Padding
ksize = [1, 2, 2, 1]
strides = [1, 2, 2, 1]
padding = 'VALID'

# max_pooling
y = tf.nn.max_pool(x, ksize, strides, padding)

In [15]:
x_data = np.array([
    [4, 3, 1, 8],
    [7, 2, 6, 3],
    [2, 0, 1, 1],
    [3, 4, 2, 5]
])

In [16]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    x = sess.run(x, feed_dict={x_image:x_data})
    y = sess.run(y, feed_dict={x_image:x_data})

In [17]:
print "The shape of X: ", x.shape
print x.reshape(4, 4)
print ""


print "The shape of y: ", y.shape
print y.reshape(2, 2)
print ""

The shape of X:  (1, 4, 4, 1)
[[ 4.  3.  1.  8.]
 [ 7.  2.  6.  3.]
 [ 2.  0.  1.  1.]
 [ 3.  4.  2.  5.]]

The shape of y:  (1, 2, 2, 1)
[[ 7.  8.]
 [ 4.  5.]]

